### ISSUE TITLE
Minor typo in hfs_model.ipynb

### ISSUE THREAD

**Issue by victorliu1231** [tvwenger/bayes_cn_hfs#7]
Very minor nitpick: in `hfs_model.ipynb`, appears to be minor typo with 'parition function' instead of 'partition function'

![Screenshot 2024-11-21 092654](https://github.com/user-attachments/assets/9458953c-63c3-46c8-b7ca-35fb72b326f9)

**Comment by tvwenger** [comment]
Thanks!
